# Generated by Django 3.0.7 on 2020-08-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
